### PR TITLE
Add option to display custom headers in the list view

### PR DESCRIPTION
**Pull request by tahirmt**
Adding an option to customize the list on iOS to be able to show any header value through the Settings page.

* The headers that should be displayed in the list can be added easily from the Settings page
* Can delete any watched header key by swiping

This is a replacement of #174 

Screenshots
---

List view

Simulator Screenshot - iPhone 14 Pro - 2023-06-04 at 13 41 12

Settings

Simulator Screenshot - iPhone 14 Pro - 2023-06-04 at 13 41 44
Simulator Screenshot - iPhone 14 Pro - 2023-06-04 at 13 41 53

### CODE REVIEW

**Comment by tahirmt** [comment]
@kean What do you think about this implementation. It's more controlled. I would like there to be a way to add default values so that if someone wants to add some headers for their app they can start with that value instead of having to do it after launching the app.

**Comment by kean** [comment]
Thanks @tahirmt, this looks great!

> instead of having to do it after launching the app.

Yes, there needs to be a way to configure it programmatically. I was considering making `UserDefaults` public in Pulse 4, so that you could do the following on the first app launch:

```swift
if isFirstAppRun {
    UserSettings.shared.displayHeaders = ["Cache-Control"]
}
```

I would also appreciate if you could target the `pulse-4` branch instead of `main`. I wasn't planning to push any new 3.x releases.

**Comment by tahirmt** [comment]
@kean  rebased `pulse-4` branch and changed the PR target. 
That sounds good. If you make it public that will work!

**Comment by tahirmt** [comment]
@kean I have a request for this to be a configurable option inside of Pulse for Mac. To be able to add headers to the list as a column or in the list view.

**Pull request merged**
