### PR TITLE
Logging system initialized correctly

### PR DESCRIPTION
**Pull request by Shivani-Bajaj**
There is a warning that appears while running the app stating Logging Error: Failed to initialize logging system. Log messages may be missing.?

So to solve this warning, an environmental variable is added to the current scheme IDEPreferLogStreaming=YES
warning fix

### CODE REVIEW

**Comment by kean** [comment]
Hey, thanks for the PR 👋 
I wonder what is the root cause of the error. It's not something that I saw before and after a quick search I couldn't find anything conclusive.
(ignore the CI errors)

**Comment by Shivani-Bajaj** [comment]
> Hey, thanks for the PR 👋 I wonder what is the root cause of the error. It's not something that I saw before and after a quick search I couldn't find anything conclusive. (ignore the CI errors)

It think it to be a bug in 15.3 and above Xcode versions. IDEPreferLogStreaming controls whether Xcode or the IDE should prefer log streaming over direct file writes. So I think in these xcode versions, this is not set by default.

Also, regarding the CI error, there was a compilation error occurring and I commented out that line to run the code. There was a lot of commented code around that, which I am not sure is referred by someone or is unused as of now. So I can remove it as well, but need to know your opinion on that.

**Comment by kean** [comment]
>  I am not sure is referred by someone or is unused as of now

It's work-in-progress code for Pulse 5.0. The latest version of the codebase is in the following PR/branch: https://github.com/kean/Pulse/pull/285.

**Comment by Shivani-Bajaj** [comment]
> > I am not sure is referred by someone or is unused as of now
> 
> It's work-in-progress code for Pulse 5.0. The latest version of the codebase is in the following PR/branch: #285.

Thanks for clarifying. So I don't need to make any changes around that. Will wait for your approval on PR if things seem fine to you.

**Pull request merged**
